Repository AY2425S1-CS2103T-T16-2/tp, pull requests merged in 2024-11, with the labels that each got.

#233 Toggle warning box severity
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#236 Refractor add command to only accept alphabets
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Buyer.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/BuyerTest.java
  src/test/java/seedu/address/model/client/NameTest.java
  src/test/java/seedu/address/model/client/SellerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: alpha-bug

#238 Update Storage Component in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ParserClasses.puml
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
Labels: severity.High, alpha-bug

#241 Update Model UML for Client
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: severity.High, alpha-bug

#242 Update model uml diagram
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
Labels: priority.High

#243 Refine vocab
  docs/UserGuide.md
Labels: priority.Medium

#245 Improve code quality and add defensive programming for meeting, addmeeting, deleteproperty related classes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/main/java/seedu/address/model/meeting/MeetingTitle.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
Labels: priority.High

#253 Add restrictions for phone number
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addbuyer.png
  docs/images/addmeeting.png
  docs/images/addseller.png
  docs/images/deletebuyer.png
  docs/images/deletemeeting.png
  docs/images/deleteseller.png
  src/main/java/seedu/address/model/client/Phone.java
Labels: priority.Medium, alpha-bug

#248 Update User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore

#256 Fix email bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/Email.java
  src/test/java/seedu/address/model/client/EmailTest.java
Labels: severity.Medium, alpha-bug

#257 Improve Code Quality For Client Classes
  docs/UserGuide.md
  src/main/java/seedu/address/model/ClientBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
Labels: priority.Medium, alpha-bug

#259 Fix name model to accept edge case
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterClientCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/NameWithoutNumber.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: alpha-bug

#260 Branch fix issues with the UI
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/PropertyCard.java
Labels: alpha-bug

#264 Deduplicate Email field
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/model/ClientBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Buyer.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Seller.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/model/ClientBookTest.java
  src/test/java/seedu/address/model/client/BuyerTest.java
  src/test/java/seedu/address/model/client/SellerTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
Labels: priority.Medium, alpha-bug

#266 Update screenshot for list feature in user guide
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/images/list.png
  docs/site.json
Labels: alpha-bug

#267 Update meeting date restrictions
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/test/data/JsonMeetingBookStorageTest/invalidAndValidMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/duplicateMeetingMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/typicalMeetingsMeetingBook.json
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/meeting/MeetingDateTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: priority.Medium, alpha-bug

#269 add some touch ups to ug
  docs/UserGuide.md
Labels: alpha-bug

#271 Fix error messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
Labels: priority.Medium, alpha-bug

#272 Fix error message
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
Labels: priority.Medium, alpha-bug

#276 Fix error message
  src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java
  src/main/java/seedu/address/model/meeting/MeetingTitle.java
Labels: priority.High, alpha-bug

#275 Fix command error format
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/FilterClientCommand.java
Labels: alpha-bug

#277 Punctuation edit
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/FilterPropertyCommand.java
  src/main/java/seedu/address/model/property/Ask.java
  src/main/java/seedu/address/model/property/Bid.java
  src/main/java/seedu/address/model/property/MatchingPrice.java
  src/main/java/seedu/address/model/property/PostalCode.java
  src/main/java/seedu/address/model/property/Type.java
  src/main/java/seedu/address/model/property/Unit.java
Labels: severity.VeryLow

#278 Fix UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/NameWithoutNumber.java
Labels: priority.High, alpha-bug

#282 Bug fixes
  docs/UserGuide.md
Labels: severity.VeryLow

#285 Fix punctuation
  docs/UserGuide.md
Labels: priority.Low

#343 Modify developer guide to add planned enhancements section
  docs/DeveloperGuide.md
Labels: planned-enhancement

#344 Remove instance of addressbook
  src/main/java/seedu/address/MainApp.java
Labels: alpha-bug

#342 Update code links in DG to point to team's repo
  docs/DeveloperGuide.md
Labels: type.Bug

#347 Remove AB3 logging
  docs/DevOps.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/java/seedu/address/logic/parser/ClientGridParserTest.java
Labels: type.Bug, priority.High, severity.Low

#349 Fix PED bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High

#350 Fix UserGuide
  docs/UserGuide.md
  docs/images/addproperty.png
  docs/images/filterproperty.png
Labels: alpha-bug

#351 Fix example email
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#352 Draft planned enhancements
  docs/DeveloperGuide.md
Labels: planned-enhancement

#353 Fix small typos
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#354 Fix Email Error Message to Align UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/Email.java
Labels: type.Bug, severity.Low

#345 Fix issue with 'use case ends'
  docs/DeveloperGuide.md
Labels: type.Bug

#358 Prepare UG final Draft
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/NameWithoutNumber.java
  src/main/java/seedu/address/model/client/Phone.java
Labels: priority.High

#360 Edit UG
  docs/UserGuide.md
Labels: priority.High

#363 Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteBuyerSequenceDiagram.puml
Labels: priority.High
