Repository AY2425S1-CS2103T-T16-2/tp, pull requests merged in 2024-10, with the labels that each got.

#21 Update read me
  README.md
  docs/images/Ui.png
Labels: priority.High

#35 Update DG for addbuyer and addseller use case
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#44 Update Developer Guide Delete Property
  docs/DeveloperGuide.md
Labels: priority.High

#43 Update Developer guide create property
  docs/DeveloperGuide.md
Labels: priority.High

#29 Update AboutUs
  docs/AboutUs.md
Labels: type.Chore, priority.High

#58 Define Buyer/ Seller Models
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ClientBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyClientBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/client/Buyer.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/ClientTypes.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/client/Seller.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/client/exceptions/ClientNotFoundException.java
  src/main/java/seedu/address/model/client/exceptions/DuplicateClientException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ClientBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonClientBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableClientBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonSerializableClientBookTest/duplicateClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/invalidClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/typicalClientClientBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/ClientTypesTest.java
  src/test/java/seedu/address/model/client/EmailTest.java
  src/test/java/seedu/address/model/client/NameTest.java
  src/test/java/seedu/address/model/client/PhoneTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/model/client/exceptions/ClientNotFoundExceptionTest.java
  src/test/java/seedu/address/model/client/exceptions/DuplicateClientExceptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/storage/JsonSerializableClientBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ClientBookBuilder.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High

#70 Make Client an abstract class
  build.gradle
  src/main/java/seedu/address/model/client/Buyer.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Seller.java
  src/test/java/seedu/address/model/client/BuyerTest.java
  src/test/java/seedu/address/model/client/SellerTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
Labels: type.Bug, severity.Medium

#73 Add logic classes for addbuyer and addseller cmds
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/JsonClientBookStorageTest/invalidAndValidClientBook.json
  src/test/data/JsonClientBookStorageTest/invalidClientClientBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: priority.High

#77 Model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PropertyBook.java
  src/main/java/seedu/address/model/ReadOnlyPropertyBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/property/UniquePropertiesList.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/model/property/exceptions/PropertyNotFoundException.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/property/UniquePropertiesListTest.java
  src/test/java/seedu/address/testutil/TypicalProperty.java
Labels: priority.High

#79 Wrap client book with constructor in edit cmd test
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Chore, priority.Low

#80 Setup Storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/main/java/seedu/address/storage/JsonPropertyBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializablePropertyBook.java
  src/main/java/seedu/address/storage/PropertyBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonPropertyBookStorageTest/invalidAndValidPropertyBook.json
  src/test/data/JsonPropertyBookStorageTest/invalidPropertyBook.json
  src/test/data/JsonPropertyBookStorageTest/notJsonFormatPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/invalidPropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/typicalPropertyPropertyBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPropertyTest.java
  src/test/java/seedu/address/storage/JsonPropertyBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerialzablePropertyBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
Labels: priority.High

#78 Add UI classes for addbuyer/ addseller [2]
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#82 Add Property logic
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#85 Delete property command
  src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PropertyBook.java
  src/main/java/seedu/address/model/property/UniquePropertiesList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/property/UniquePropertiesListTest.java
  src/test/java/seedu/address/testutil/TypicalProperty.java
Labels: priority.High

#89 Update User Guide For Add Buyer/ Seller Commands
  docs/UserGuide.md
  docs/images/addbuyer.png
  docs/images/addseller.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Phone.java
  src/test/data/JsonClientBookStorageTest/invalidAndValidClientBook.json
  src/test/data/JsonClientBookStorageTest/invalidClientClientBook.json
  src/test/data/JsonSerializableClientBookTest/typicalClientClientBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High

#91 Update DeveloperGuide for add property
  docs/UserGuide.md
  docs/images/addproperty.png
Labels: priority.High

#93 Add addproperty to summary table in UG
  docs/UserGuide.md
Labels: priority.Medium

#101 Update images for client commands in user guide
  docs/UserGuide.md
  docs/images/addbuyer.png
  docs/images/addseller.png
  docs/images/deletebuyer.png
  docs/images/deleteseller.png
Labels: type.Bug

#108 Type
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/property/PostalCode.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/PropertyType.java
  src/main/java/seedu/address/model/property/Type.java
  src/main/java/seedu/address/model/property/Unit.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/test/data/JsonPropertyBookStorageTest/invalidAndValidPropertyBook.json
  src/test/data/JsonPropertyBookStorageTest/invalidPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/invalidPropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/typicalPropertyPropertyBook.json
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/PropertyTypeTest.java
  src/test/java/seedu/address/model/property/TypeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPropertyTest.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
  src/test/java/seedu/address/testutil/TypicalProperty.java
Labels: type.Enhancement

#106 Set up Meeting storage
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/ReadOnlyMeetingBook.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/main/java/seedu/address/model/meeting/MeetingTitle.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonMeetingBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableMeetingBook.java
  src/main/java/seedu/address/storage/MeetingBookStorage.java
  src/test/data/JsonMeetingBookStorageTest/invalidAndValidMeetingBook.json
  src/test/data/JsonMeetingBookStorageTest/invalidMeetingMeetingBook.json
  src/test/data/JsonMeetingBookStorageTest/notJsonFormatMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/duplicateMeetingMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/invalidMeetingMeetingBook.json
  src/test/data/JsonSerializableMeetingBookTest/typicalMeetingsMeetingBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/meeting/MeetingDateTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/model/meeting/MeetingTitleTest.java
  src/test/java/seedu/address/model/meeting/UniqueMeetingListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/address/storage/JsonMeetingBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMeetingBookTest.java
  src/test/java/seedu/address/testutil/MeetingBookBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: priority.High

#115 Implement deletemeeting
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterClientCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListBuyersCommandTest.java
  src/test/java/seedu/address/logic/commands/ListClientsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPropertiesCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSellersCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Story, priority.High

#111 Trade property feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/property/Ask.java
  src/main/java/seedu/address/model/property/Bid.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/test/data/JsonPropertyBookStorageTest/invalidAndValidPropertyBook.json
  src/test/data/JsonPropertyBookStorageTest/invalidPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/invalidPropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/typicalPropertyPropertyBook.json
  src/test/java/seedu/address/logic/MessagesTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/property/AskTest.java
  src/test/java/seedu/address/model/property/BidTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPropertyTest.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
  src/test/java/seedu/address/testutil/TypicalProperty.java
Labels: type.Enhancement, priority.Medium

#116 Standardize error messages for commands
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
  src/main/java/seedu/address/logic/commands/FilterClientCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: priority.Medium

#114 Filter
  src/main/java/seedu/address/logic/commands/FilterPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterPropertyCommandParser.java
  src/main/java/seedu/address/model/property/Ask.java
  src/main/java/seedu/address/model/property/Bid.java
  src/main/java/seedu/address/model/property/MatchingPrice.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterPropertyCommandParserTest.java
  src/test/java/seedu/address/model/property/MatchingPriceTest.java
Labels: type.Enhancement, priority.Medium

#125 Update User and Developer Guides for addbuyer/seller and deletemeeting Commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/deletemeeting.png
Labels: priority.High

#128 Standardise error message
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/FilterPropertyCommand.java
Labels: severity.VeryLow

#132 Add meeting command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/model/meeting/UniqueMeetingListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: priority.High

#137 Uml
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/FilterPropertySequenceDiagram.puml
Labels: priority.High

#149 Add UML Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddBuyerSequenceDiagram.puml
  docs/diagrams/DeleteSellerSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Enhancement, priority.High

#152 Add assertions and logging to client classes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/model/ClientBook.java
  src/main/java/seedu/address/model/client/Buyer.java
  src/main/java/seedu/address/model/client/ClientTypes.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/client/Seller.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
Labels: priority.Medium

#154 Defensive coding
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/FilterPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterPropertyCommandParser.java
  src/main/java/seedu/address/model/property/Ask.java
  src/main/java/seedu/address/model/property/Bid.java
  src/main/java/seedu/address/model/property/MatchingPrice.java
  src/main/java/seedu/address/model/property/PostalCode.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/Type.java
  src/main/java/seedu/address/model/property/Unit.java
Labels: priority.High

#156 Update UG and DG for add meeting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addmeeting.png
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
Labels: priority.High

#167 Developer guide
  docs/UserGuide.md
  docs/images/addproperty.png
  docs/images/filterproperty.png
Labels: priority.High

#169 Fix md syntax
  docs/UserGuide.md
Labels: type.Bug

#174 Fix bugs for delete and filter commands
  src/main/java/seedu/address/logic/parser/DeleteBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterClientCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterClientCommandParserTest.java
Labels: alpha-bug

#180 Update UML diagram
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
Labels: severity.VeryLow

#203 Fix add buyer bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/model/client/Phone.java
Labels: priority.High, alpha-bug

#210 Solve ask and bid of number issues for add property
  src/main/java/seedu/address/model/property/Ask.java
  src/main/java/seedu/address/model/property/Bid.java
  src/main/java/seedu/address/model/property/MatchingPrice.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/property/AskTest.java
  src/test/java/seedu/address/model/property/BidTest.java
  src/test/java/seedu/address/model/property/MatchingPriceTest.java
Labels: priority.High

#209 Update error messages for addproperty
  src/main/java/seedu/address/model/property/Ask.java
  src/main/java/seedu/address/model/property/Bid.java
  src/main/java/seedu/address/model/property/MatchingPrice.java
  src/main/java/seedu/address/model/property/PostalCode.java
  src/main/java/seedu/address/model/property/Type.java
  src/main/java/seedu/address/model/property/Unit.java
Labels: priority.High

#215 Fix developer and user guide
  docs/DeveloperGuide.md
  docs/images/Ui.png
Labels: alpha-bug

#214 Fix user guide for filterclient and addmeeting commands
  docs/UserGuide.md
Labels: alpha-bug

#213 Fix error for chain commands
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
Labels: alpha-bug

#211 Solve ask and bid of number issues for filterproperty
  src/main/java/seedu/address/model/property/Unit.java
  src/test/java/seedu/address/model/property/UnitTest.java
Labels: priority.High

#217 Standardize developer guide for deleteclient command
  docs/DeveloperGuide.md
Labels: alpha-bug

#222 Fix too many parameters in command, addproperty and filterproperty
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterPropertyCommandParser.java
  src/test/java/seedu/address/logic/parser/AddPropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterPropertyCommandParserTest.java
Labels: priority.High, alpha-bug

#224 Update DG, UG, Error Messages for add meeting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addmeeting.png
  docs/images/deleteproperty.png
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
Labels: priority.High

#226 Remove extra prefix issue
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterClientCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/AddBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: alpha-bug

#232 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/property/Type.java
Labels: type.Chore, priority.High
